openapi: 3.0.1
info:
  title: graph-nmap
  description: ''
  x-cortex-git:
    github:
      repository: JupiterOne/graph-nmap
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: graph-nmap
  x-cortex-service-groups:
    - tier-4
